In [2]:
import torch

In [3]:
matrix1 = torch.rand(4,4)
print(matrix1)

tensor([[0.1440, 0.6562, 0.7519, 0.1477],
        [0.7803, 0.3915, 0.0847, 0.0356],
        [0.2056, 0.4585, 0.0167, 0.4879],
        [0.5024, 0.6819, 0.2055, 0.6674]])


In [4]:
matrix2 = torch.rand(4,4)
print(matrix2)

tensor([[0.8396, 0.3798, 0.4620, 0.4834],
        [0.7694, 0.3067, 0.1173, 0.7598],
        [0.0173, 0.7875, 0.0473, 0.5616],
        [0.0159, 0.7740, 0.5371, 0.6049]])


In [5]:
result = torch.matmul(matrix2,matrix1)
print(result)

tensor([[0.7551, 1.2411, 0.7705, 0.6855],
        [0.7560, 1.1969, 0.7626, 0.6888],
        [0.9089, 0.7243, 0.1959, 0.4285],
        [1.0207, 0.9723, 0.2108, 0.6957]])


### Torch.randn_like

#### 参数

- `input`：（**Tensor**）指定大小的张量，`randn_like` 会生成与此张量相同大小的随机数张量。
  
- `dtype`（可选）：生成的随机张量的数据类型，默认为 `None`，表示与 `input` 张量的数据类型相同。
  
- `layout`（可选）：生成的随机张量的布局，默认为 `None`。
  
- `device`（可选）：生成的随机张量将存储在的设备，默认为 `None`，即与 `input` 张量相同的设备。

- `requires_grad`（可选）：指示生成的张量是否需要梯度，默认为 `False`。

#### 返回值

- `Tensor`：生成与 `input` 张量相同大小的张量，其中包含从标准正态分布中抽取的随机数。


In [6]:
import torch

# 创建一个形状为 (2, 3) 的张量
input_tensor = torch.empty(2, 3)

# 使用 randn_like 生成一个与 input_tensor 相同大小的随机数张量
random_tensor = torch.randn_like(input_tensor)
print(input_tensor)
print(random_tensor)


tensor([[6.3058e-44, 6.8664e-44, 7.0065e-44],
        [6.3058e-44, 6.7262e-44, 6.8664e-44]])
tensor([[-0.5004, -0.2818,  1.0054],
        [ 0.2337,  2.2118, -1.6451]])


In [7]:
result = torch.add(input_tensor,random_tensor)
print(result)

tensor([[-0.5004, -0.2818,  1.0054],
        [ 0.2337,  2.2118, -1.6451]])


In [1]:
import torch

In [13]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [11]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [6]:
import torch
x = torch.arange(16).reshape(2,2, 4)
print("Original Tensor:\n", x)

# 使用view改变形状
y = x.view(2,2,2,2)
print("Reshaped Tensor:\n", y)

Original Tensor:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]])
Reshaped Tensor:
 tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]])
